Sprint 3/step 1
blurryfacebeat/react-burger pull request #4
Opened 2024-06-04 12:21 UTC by blurryfacebeat

Sprint 3/step 1

2024-06-04 13:55 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- <https://disk.yandex.com/i/H8cEa5DupgPDvA> - у вас возникает ошибка при оформлении заказа;

### **Более мелкие замечания отмечены в коде.**

2024-06-04 13:55 UTC, ArslanMustafin commented on src/api/api.utils.ts
> +      ...options,
**Можно лучше:**

я бы вытащил из options отдельно `headers`, а уже потом можно раскрывать)), потому что сейчас у вас идёт перезапись `headers` (Пример с `createOrder`).

2024-06-04 13:55 UTC, ArslanMustafin commented on src/api/create-order.ts
> +    ).then(checkResponse);
**Надо исправить:**

тут не нужно использовать `checkResponse`. Т.к. это уже есть в `fetchWithRefresh`

2024-06-04 13:55 UTC, ArslanMustafin commented on src/components/burger-ingredients/ui/burger-ingredients-details/burger-ingredients-details.tsx
> +  }, [ingredients, params.ingredientId, dispatch]);
**Надо исправить:**

Лучше делать 1 запрос ингредиентов в компоненте app.

А также, экшен должен выполнять только 1 действие, а не несколько. Тут лучше добавить селектор, чтобы он из списка ингредиентов находил нужный.

2024-06-04 13:55 UTC, ArslanMustafin commented on src/components/burger-ingredients/ui/burger-ingredients-details/burger-ingredients-details.tsx
> +}) => {
**Можно лучше:**

по хорошему, тут не должно быть никакой логики, только вывод ингредиента, всю логику лучше реализовать выше, а сюда передавать нужный ингредиент через пропс. Тогда этот компонент не будет зависить от глобального стейта, и можно будет вывести любой ингредиент, а не только тот, который выбрали

2024-06-04 13:55 UTC, ArslanMustafin commented on src/components/forgot-password/forgot-password.tsx
> +          />
**Надо исправить:**

там где у вас идут поля с email, нужно использовать [EmailInput](https://yandex-practicum.github.io/react-developer-burger-ui-components/docs/email-input) и можно убрать _@ts-expect-error_) Поправьте во всём проекте. На остальных можете пока оставить _@ts-expect-error_.

2024-06-04 13:55 UTC, ArslanMustafin commented on src/components/profile/ui/profile-info/hooks/use-update-profile.ts
> +  const [password, setPassword] = useState<string>(oldPassword.current);
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

```js
export function useForm<T>(inputValues: T) {

    const [values, setValues] = useState<T>(inputValues);

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      const {value, name} = event.target;
      setValues({...values, [name]: value});
    };

    return {values, handleChange, setValues};

}

// как использовать:

type FormStateType = {
  name:string;
  password:string;
}

const initialFormState: FormStateType = {
  name: 'name',
  password: '',
}

const {...} = useForm<FormDataType>(initialFormState)
```

2024-06-04 13:55 UTC, ArslanMustafin commented on src/store/actions/profile.action.ts
> +    if (accessTokenLocalStorage.get()) {
**Можно лучше:**

Лучше всегда писать условия от противного и делать return. 

Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2024-06-04 14:47 UTC, blurryfacebeat commented on src/components/profile/ui/profile-info/hooks/use-update-profile.ts
> +  const [password, setPassword] = useState<string>(oldPassword.current);
Нет времени сейчас переписывать, но спасибо, потом воспользуюсь

2024-06-05 03:04 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-06-05 03:20 UTC, merged